### ISSUE TITLE
Server Display Error

### ISSUE THREAD

**Issue by TimeCodings** [LabyMod/server-media#1398]
Since changing the direct server-domain in the manifest file from "direct_ip": "wysteria.net", → "direct_ip": "wysteria.de" (it also got merged 2 days ago), the site on laby.net is glitched: https://laby.net/server/wysteria. wysteria.de is still listed like a normal server (in the LabyMod Client too) and, however, wysteria.net is now listed without the stats.

**Comment by DoJapHD** [comment]
That's probably something that @JakobBruening needs to have a look at

**Comment by S42yt** [comment]
Yo the server is permanantly offline so it was announced on their official dc
