### ISSUE TITLE
Nidocraft Network - No logo on laby.net

### ISSUE THREAD

**Issue by Wqsknijper** [LabyMod/server-media#255]
Hi there!

I was wondering why our logo's do not show on the Nidocraft laby.net site.
![image](https://user-images.githubusercontent.com/65192978/166516207-bf7a1ab9-f524-4cef-a809-e6142dde9749.png)
![image](https://user-images.githubusercontent.com/65192978/166516303-6b809589-5716-4e71-a0d6-41a50b42119a.png)
When I try to visit the .webp icon it doesn't exist while when I visit the .png icon, it does exist.

Did I do something wrong or is it on your side?

Thanks in advance 😃,
Wqsknijper - Manager on Nidocraft Network

**Comment by l3nnartt** [comment]
Works for me, have you tried disabling your adblocker?

**Comment by JakobBruening** [comment]
Fixed! (Caching issue)
Additionally, I would prefer another color for the button - It's hard to read the text ;) - Feel free to create a PR on that!

BR, Jakob

**Comment by Wqsknijper** [comment]
> Fixed! (Caching issue) Additionally, I would prefer another color for the button - It's hard to read the text ;) - Feel free to create a PR on that!
> 
> BR, Jakob

Thank you! I've created a PR for that + added some icons for the gamemodes.

Have a nice day!
