### ISSUE TITLE
Server Icon not working

### ISSUE THREAD

**Issue by ManciDRaffy** [LabyMod/server-media#270]
Das Server-Icon wird auf der Website https://laby.net/server/laudynetwork nicht angezeigt.

Das Bild funktioniert aber einwandfrei deswegen ist die Frage warum das nicht funktioniert? 
Nachdem ja alles richtig ist. Im Pull Request wollte mir nicht geholfen werden.

#266

**Comment by JakobBruening** [comment]
Hey @ManciDRaffy!

Danke für das Öffnen des Issues - Die Antwort hat etwas gedauert und war in der PR nicht schnell genug, da ich ein bisschen im Hintergrund umgebaut habe und das Zeit in Anspruch genommen hat, damit ich dir genauere Infos geben kann! 

Grundlegend: @l3nnartt hat in der PR Recht gehabt :) - Jedoch war dies nicht das einzige Problem.

**Problem 1: Server directory**
Das Hauptproblem war ein Fehler in den Filenames (x2 statt 2x). Daher wurden die Files beim Deployment nicht korrekt hinzugefügt und konnten nicht auf LABY.net angezeigt werden, behoben habe ich dies hier: https://github.com/LabyMod/server-media/commit/7fb81eeda6eb1653a3bea725eff3389e72476891

**Problem 2: Deployment**
Deployment wurde die letzten Male manuell übernommen - Wie es @l3nnartt richtig erkannt hat gab es einen Fehler im Workflow :)
Auch dieses Problem ist nun gelöst, es sollte, auch in Bezug auf Caching, in Zukunft keine Probleme mehr beim Deployment geben. Server-Daten werden nun in Zukunft stündlich aktualisiert.
*Kurz* dokumentiert ist der Prozess hier: https://github.com/LabyMod/server-media#publish-information-for-contributors

Also; Keine Probleme mehr in Zukunft und alles behoben!
Danke dir/euch beiden für die Geduld!

Viele Grüße,
Jakob
