### ISSUE TITLE
reberion.eu logo not working

### ISSUE THREAD

**Issue by suddlefrv** [LabyMod/server-media#344]
Laby.net https://laby.net/server/reberion icon not working

**Comment by suddlefrv** [comment]
and background tho

**Comment by scrummer** [comment]
@suddlefrv See https://github.com/LabyMod/server-media/blob/master/docs/Files.md#filestructure

The server is (at least) missing the two mandatory files:
![image](https://user-images.githubusercontent.com/15173170/198361148-341cc8e2-baa6-4673-8beb-f09b0a7ed4a6.png)

**Comment by suddlefrv** [comment]
how can i update images ? i update manifest but i cant update icons. Merge error

**Comment by JakobBruening** [comment]
Make sure you are up-to-date with the master branch. Then, just replace the image and create a Pull request - This should work!

**Comment by JakobBruening** [comment]
I will close the issue due to inactivity. If you have further problems/questions, feel free to re-open!
