### ISSUE TITLE
Player stats detection not working

### ISSUE THREAD

**Issue by LeStegii** [LabyMod/server-media#415]
If the bot detects an invalid player stats link, it tells you to add {userName} to the link. If you remove the whole link instead, it doesn't seem to update the "Changes requested" label.

See #414

**Comment by JakobBruening** [comment]
There is no automatic approval by the workflow and there is no option to "remove the state".
So after you fixed it, you have to wait for a manual review. The workflow will send a comment again if there are other issues, but not if everything is o.k. after the fix.

So, in your case there are some requests from my side still open, the script cannot find any issues anymore - So from the technical side, everything is okay!

Feel free to write if you still have questions! 

Best regards
Jakob

**Comment by UeberallGebannt** [comment]
I see, thank you for your detailed explanation ^^
