### ISSUE TITLE
Wildcards not working?

### ISSUE THREAD

**Issue by MaximFiedler** [LabyMod/server-media#622]
Three days ago, [my pull request](https://github.com/LabyMod/server-media/pull/609/commits/38065847fecb3860a6c4dde91d9670636b2f4bbd) to modify the wildcards in my manifest.json was merged. However, despite this change, my .de domain is still missing the server banner, icon and quickjoin in the client. Is something wrong, or should I just wait a bit longer?

_(My server is reachable over both domains at any time)_

**Comment by JakobBruening** [comment]
Fixed. Thank you for your report :)
