### ISSUE TITLE
Cannot see changes on LABY.net

### ISSUE THREAD

**Issue by FlynnLG** [LabyMod/server-media#75]
Hello,
I created a directory under minecraft_servers (flynnlg) 2 days ago but I cannot see the logo, background and more at laby.net. My pull request was accepted and is closed. What can I do?
With best regards,
Flynn_LG.

**Comment by scrummer** [comment]
Hi @FlynnLG 

This issue can have multiple reasons. Therefore I need you to answer these quesions:
- Is your server up and running?
- Is your server a premium or a cracked server?

Maybe this can be the cause.

BR
Scrummer

**Comment by FlynnLG** [comment]
Hey @scrummer

The answers to your questions.

'Is your server up and running?':
Yes my server/network is running, but we are in currently in maintenance.

'Is your server a premium or a cracked server?':
It's a premium server.

**Comment by scrummer** [comment]
@FlynnLG Just checked it again - seems to work now:
https://laby.net/server/flynnlg.de

**Comment by FlynnLG** [comment]
<img width="2525" alt="Bildschirmfoto 2021-07-20 um 13 24 49" src="https://user-images.githubusercontent.com/62892734/126316159-6d77f776-80fc-4c23-9b43-982969c91ed2.png">
I don't see anything.

**Comment by enno123** [comment]
Same issue here

**Comment by FlynnLG** [comment]
Very weird...

**Comment by scrummer** [comment]
We will have a look at it...

**Comment by JakobBruening** [comment]
@FlynnLG Currently, your server page is unavailable because your server is not online. Please bring it online again, so I can search for the main issue.

![Bildschirmfoto 2021-07-20 um 18 37 56](https://user-images.githubusercontent.com/45363287/126362365-49850222-a3ab-443c-9dae-e80b672b63a1.png)
![Bildschirmfoto 2021-07-20 um 18 37 24](https://user-images.githubusercontent.com/45363287/126362291-2bbe58f9-f51e-4fef-8d5e-005ec612c281.png)

**Comment by JakobBruening** [comment]
And regarding your server @enno123:
You made another mistake in your PR (and yes, I also made a mistake in the review ;D).
The `server_name` must have the directory name: https://github.com/LabyMod/server-media/commit/2ba98dd38a1f4865272c0dff2790e2378597d4ba

**Comment by FlynnLG** [comment]
Hello @JakobBruening,
sorry, i tested something with the proxy - should be back online.
With best regards,
Flynn_LG.

**Comment by FlynnLG** [comment]
I think, it was my problem: https://github.com/LabyMod/server-media/pull/76 😅

**Comment by FlynnLG** [comment]
Thank you! When will everything be available on laby.net?

**Comment by JakobBruening** [comment]
Now ;)
https://laby.net/server/flynnlg

![Bildschirmfoto 2021-07-20 um 20 47 51](https://user-images.githubusercontent.com/45363287/126378899-5e324018-4197-45b5-901e-ebce142c3253.png)

**Comment by FlynnLG** [comment]
Thank you very much :)
Have a nice day!
With best regards,
Flynn_LG.
