### ISSUE TITLE
Wildcards not working and missing image on laby.net 

### ISSUE THREAD

**Issue by MeHaVr** [LabyMod/server-media#778]
**Hello** 

Banner is not displaying in the server list,
and the manifest is not applied on the [website.](https://laby.net/server/lythia.de) 

Please HELP :)

**Comment by MeHaVr** [comment]
Hello ?

**Comment by Jxelsw** [comment]
Ok

**Comment by Jxelsw** [comment]
@JakobBruening

**Comment by MeHaVr** [comment]
Its been 1 month 

no message no update 
![image](https://github.com/LabyMod/server-media/assets/122679220/2b0347c9-4d26-45c5-a7ad-80aee18c0990)
![image](https://github.com/LabyMod/server-media/assets/122679220/c976826c-3a1c-469c-b4a8-c9e68e939e89)

**Comment by Jxelsw** [comment]
Bruder ich warte auch schon seit Jahren ich geb die Hoffnung auf

**Comment by MeHaVr** [comment]
ich auch gleich

**Comment by Jxelsw** [comment]
Ja ist Ok

**Comment by JakobBruening** [comment]
Hallo ihr beiden!
Vielen Dank für die Meldung(en) und auch für das lange Warten.

Bitte habt Verständnis dafür, dass solch spezifischen Fehler auch mal ein bisschen dauern können, da sich andere Dinge dazwischen drängeln. Ich bin ja schließlich direkt assigned worden und das Issue ist nicht ohne Aktion offen geblieben :)

So, und wenn es jetzt noch Probleme oder Fragen gibt, gerne das Issue neu öffnen oder direkt schreiben.

Liebe Grüße
Jakob
