### ISSUE TITLE
Server images not loaded after 2 weeks

### ISSUE THREAD

**Issue by Jxelsw** [LabyMod/server-media#816]
Hello I am the owner of BlockLeben

My pull request was accepted 2 or 3 weeks ago and still nothing has changed.
It is neither in Minecraft nor on the Laby.net page the changes are displayed

Is this normal?

**Comment by MeHaVr** [comment]
True

**Comment by JakobBruening** [comment]
Hey!
Thank you for waiting. We have fixed the issue. Your server data should now be visible on laby.net!
If there are still any issues, feel free to re-open the issue!

BR, Jakob

**Comment by Jxelsw** [comment]
Nur eine Frage: Wie lang dauert es bis meine Änderungen vorgenommen werden? Wird es wieder so lange dauern?
